name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  INSTALL_PREFIX: install
  BUILD_TYPE: Release

jobs:
  tests:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-latest

    env:
      CC: gcc-9
      CXX: g++-9

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: ${{ env.INSTALL_PREFIX }}
          key: ${{ hashFiles('cmake/install-dependencies.cmake') }}

      - name: Install dependencies
        run: cmake -P cmake/install-dependencies.cmake

      - name: Configure
        run: cmake -S . -B build -D CMAKE_INSTALL_PREFIX=$INSTALL_PREFIX
          -D CMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build
