name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-latest

    env:
      CC: gcc-9
      CXX: g++-9

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: .ubpm
          key: ${{ hashFiles('dependencies.cmake') }}

      - uses: friendlyanon/ubpm@pre-v2
        id: ubpm

      - name: Configure
        env:
          UBPM_MODULE_PATH: ${{ steps.ubpm.outputs.location }}
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
